### ISSUE TITLE
Code Help Urgent Urgent

### ISSUE THREAD

**Issue by jj12345677** [wwwccttoo/Code-for-AL-PSST-Mesbah-lab#1]
In function file **ftir_NN.m**, _outputs(:,3) = -outputs_now(:,3)/1000;
    outputs(:,2) = outputs_now(:,2)-param._
Why divide by 1000 and why subtract _param_ in these two lines of code (is _param_ the power value to be constrained?).

**Comment by wwwccttoo** [comment]
> In function file **ftir_NN.m**, _outputs(:,3) = -outputs_now(:,3)/1000; outputs(:,2) = outputs_now(:,2)-param._ Why divide by 1000 and why subtract _param_ in these two lines of code (is _param_ the power value to be constrained?).

I recall it is because I am not sure if the GP training inside ADMMBO will automatically take care the normalization of the outputs. Therefore, dividing 1000 will bring the magnitude back to 1. If the GP training inside ADMMBO will automatically rescale the objective, it should be fine though.
And yes, the param is the value of the power you would like to use.

**Comment by jj12345677** [comment]
Thank you very much for your prompt and insightful response. I was genuinely surprised and deeply appreciative of the speed and thoughtfulness of your reply. Your work is incredibly valuable, and it's an honor to engage with you on these topics.

I have a further inquiry regarding the methodologies employed in our optimization objectives. Could you kindly elaborate on the differences between the evaluate_model used in the "AL_Space_Exploration_for_NOx_Production_Rate_with_Power_constraint" and the Pintopin_DNN_model that was developed during the "BO_for_ANN_Hyperparameter_Selection"? 

Looking forward to your esteemed response





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wwwccttoo/Code-for-AL-PSST-Mesbah-lab"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月19日(星期二) 下午3:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wwwccttoo/Code-for-AL-PSST-Mesbah-lab] Code Help Urgent Urgent (Issue #1)





  
In function file ftir_NN.m, outputs(:,3) = -outputs_now(:,3)/1000; outputs(:,2) = outputs_now(:,2)-param. Why divide by 1000 and why subtract param in these two lines of code (is param the power value to be constrained?).
  
I recall it is because I am not sure if the GP training inside ADMMBO will automatically take care the normalization of the outputs. Therefore, dividing 1000 will bring the magnitude back to 1. If the GP training inside ADMMBO will automatically rescale the objective, it should be fine though.
 And yes, the param is the value of the power you would like to use.

**Comment by wwwccttoo** [comment]
> Thank you very much for your prompt and insightful response. I was genuinely surprised and deeply appreciative of the speed and thoughtfulness of your reply. Your work is incredibly valuable, and it's an honor to engage with you on these topics. I have a further inquiry regarding the methodologies employed in our optimization objectives. Could you kindly elaborate on the differences between the evaluate_model used in the "AL_Space_Exploration_for_NOx_Production_Rate_with_Power_constraint" and the Pintopin_DNN_model that was developed during the "BO_for_ANN_Hyperparameter_Selection"? Looking forward to your esteemed response
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "wwwccttoo/Code-for-AL-PSST-Mesbah-lab" ***@***.***&gt;; 发送时间:&nbsp;2024年3月19日(星期二) 下午3:57 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [wwwccttoo/Code-for-AL-PSST-Mesbah-lab] Code Help Urgent Urgent (Issue #1) In function file ftir_NN.m, outputs(:,3) = -outputs_now(:,3)/1000; outputs(:,2) = outputs_now(:,2)-param. Why divide by 1000 and why subtract param in these two lines of code (is param the power value to be constrained?). I recall it is because I am not sure if the GP training inside ADMMBO will automatically take care the normalization of the outputs. Therefore, dividing 1000 will bring the magnitude back to 1. If the GP training inside ADMMBO will automatically rescale the objective, it should be fine though. And yes, the param is the value of the power you would like to use. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

The model developed in 'BO_for_ANN_Hyperparameter_Selection' is that the model hyperparameters are tuned by BO. For more information, please refer to A.D. Bonzanini, K. Shao, D.B. Graves, S. Hamaguchi, and A. Mesbah. Foundations of machine learning for low-temperature plasmas: Methods and case studies, Plasma Sources Science and Technology, 32 (2), 024003, 2023. 
Once a good model is identified, this model then is used as a surrogate of the experiment for 'AL_Space_Exploration_for_NOx_Production_Rate_with_Power_constraint'
